# Exported from Render - Combined Configuration
# SECURITY: Production-ready deployment with managed PostgreSQL
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    # Existing VST Converter Service
    - type: web
      name: vstconverter
      runtime: python
      repo: https://github.com/SheriffAbdullah/vstconverter
      plan: free
      region: singapore
      buildCommand: pip install -r requirements.txt
      startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
      autoDeployTrigger: commit
 
    # Jade SmartBank API Service
    - type: web
      name: jade-smartbank-api
      env: docker
      repo: https://github.com/sheriffabdullah/jade-smartbank 
      region: singapore
      plan: free
      dockerfilePath: ./Dockerfile
      envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: jade-smartbank-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: CORS_ORIGINS
        value: '["https://jade-smartbank-frontend.vercel.app","https://*.vercel.app","http://localhost:5173","http://localhost:3000"]'
      - key: RATE_LIMIT_ENABLED
        value: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: REFRESH_TOKEN_EXPIRE_DAYS
        value: 7
      - key: LOG_LEVEL
        value: INFO
      healthCheckPath: /health
      autoDeployTrigger: commit

    databases:
    - name: jade-smartbank-db
      databaseName: jade_smartbank
      user: jade_admin
      plan: free
      region: singapore
      ipAllowList: []